volumes:
  rnrapi_local_postgres_data: {}

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - rnrapi_local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.local.postgres.env

  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    env_file:
      - ./.local.postgres.env
      - ./.local.api.env
    depends_on:
      - postgres

  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - "443:443"
    volumes:
      - ./local.conf:/etc/nginx/conf.d/default.conf
      - ./selfsigned.crt:/etc/nginx/ssl/selfsigned.crt
      - ./selfsigned.key:/etc/nginx/ssl/selfsigned.key
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - api
