volumes:
  rnrapi_local_postgres_data: {}

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - rnrapi_local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.local.postgres.env
    networks:
      - rnrapi

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    env_file:
      - ./.local.postgres.env
      - ./.local.api.env
    depends_on:
      - postgres
    networks:
      - rnrapi

networks:
  rnrapi:
    driver: bridge
