#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';
  CREATE DATABASE $POSTGRES_DB OWNER $POSTGRES_USER;
EOSQL
